/* ============================================
   API URL Constants — mirrors Flutter ApiUrl class
   ============================================ */

// Use same-origin relative paths — works on any domain
const API_BASE = window.location.origin + '/';
const API_URL = API_BASE + 'api';

const ApiUrl = {
  // --- Auth ---
  register: '/auth/register',
  login: '/auth/login',
  sendEmailCode: '/auth/sendCode',
  verifyCode: '/auth/verifyCode',
  sendPhoneCode: '/auth/sendSmsCode',
  resetPassword: '/auth/resetPassword',

  // --- Common ---
  config: '/common/config',
  fileUpload: '/common/fileUpload',
  getArea: '/common/getArea',
  getCountry: '/common/getCountry',
  getLocation: '/common/location',
  getContinents: '/common/getContinents',
  getContinentsList: '/common/getContinentsList',
  getType: '/common/getType',
  getTypeClass: '/common/getTypeClass',
  getInformationClass: '/common/getInformationClass',
  guideType: '/common/getGuideType',
  homeData: '/common/home',
  homeSearch: '/common/homeSearch',
  search: '/common/search',

  // --- City ---
  cityList: '/city/lists',
  cityOptions: '/city/options',
  cityClass: '/city/class',
  cityInfo: '/city/info',
  cityGuide: '/city/guide',
  guideInfo: '/city/guideInfo',
  reserveGuide: '/city/reserveGuide',
  cityAttraction: '/city/attraction',
  cityRestaurant: '/city/restaurant',
  cityShopping: '/city/shopping',
  cityAccommodation: '/city/accommodation',
  cityTransportation: '/city/transportation',
  cityFacility: '/city/facility',
  cityActivity: '/city/activity',
  cityTicket: '/city/ticket',
  cityContent: '/city/contentInfo',
  contentEvaluate: '/city/contentEvaluate',
  addContentEvaluate: '/city/addContentEvaluate',
  addContentReserve: '/city/addContentReserve',
  followGuide: '/city/guideFollow',
  unfollowGuide: '/city/guideUnFollow',
  followCompany: '/city/companyFollow',
  followShop: '/city/shopFollow',

  // --- User ---
  userIndex: '/user/index',
  memberInfo: '/user/numberInfo',
  editUserInfo: '/user/editInfo',
  deleteUser: '/user/delAccount',
  bindPhone: '/user/bindPhone',
  contactUs: '/user/contactUs',
  feedback: '/user/feedback',
  inviteLog: '/user/inviteLog',
  userReserveGuide: '/user/reserveGuide',
  userReserveGuideInfo: '/user/reserveGuideInfo',
  userReserveGuideEdit: '/user/reserveGuideEdit',
  userReserveGuideCancel: '/user/reserveGuideCancel',
  userReserveGuideDelete: '/user/reserveGuideDel',
  userReserveCompany: '/user/reserveCompany',
  userReserveCompanyInfo: '/user/reserveCompanyInfo',
  userReserveCompanyEdit: '/user/reserveCompanyEdit',
  userReserveCompanyCancel: '/user/reserveCompanyCancel',
  userReserveCompanyDelete: '/user/reserveCompanyDel',
  addressLists: '/user/address',
  addressAdd: '/user/addressAdd',
  addressEdit: '/user/addressEdit',
  addressDelete: '/user/addressDelete',
  applyGuide: '/user/applyGuide',
  applyGuideInfo: '/user/applyGuideInfo',
  applyCompany: '/user/applyCompany',
  applyCompanyInfo: '/user/applyCompanyInfo',
  userRecord: '/user/loginRecord',

  // --- Information ---
  informationLists: '/information/lists',
  informationInfo: '/information/info',
  informationEvaluate: '/information/evaluate',
  addInformationEvaluate: '/information/addEvaluate',

  // --- Guide ---
  guideChangeCity: '/guide/changeCity',
  guidePublishCity: '/guide/publishCity',
  guideCityList: '/guide/cityList',
  guideCityInfo: '/guide/city',
  guideEditCity: '/guide/editCity',
  guideDelCity: '/guide/delCity',
  guideAttraction: '/guide/attraction',
  guideAttractionAdd: '/guide/attractionAdd',
  guideAttractionInfo: '/guide/attractionInfo',
  guideAttractionEdit: '/guide/attractionEdit',
  guideAttractionDel: '/guide/attractionDel',
  guideTransportation: '/guide/transportation',
  guideTransportationAdd: '/guide/transportationAdd',
  guideTransportationInfo: '/guide/transportationInfo',
  guideTransportationEdit: '/guide/transportationEdit',
  guideTransportationDel: '/guide/transportationDel',
  guideFacility: '/guide/facility',
  guideFacilityAdd: '/guide/facilityAdd',
  guideFacilityInfo: '/guide/facilityInfo',
  guideFacilityEdit: '/guide/facilityEdit',
  guideFacilityDel: '/guide/facilityDel',
  guideActivity: '/guide/activity',
  guideActivityAdd: '/guide/activityAdd',
  guideActivityInfo: '/guide/activityInfo',
  guideActivityEdit: '/guide/activityEdit',
  guideActivityDel: '/guide/activityDel',
  guideInformation: '/guide/information',
  guideInformationAdd: '/guide/informationAdd',
  guideInformationInfo: '/guide/informationInfo',
  guideInformationEdit: '/guide/informationEdit',
  guideInformationDel: '/guide/informationDel',
  guideReserve: '/guide/reserve',
  guideReserveInfo: '/guide/reserveInfo',
  guideConfirmReserve: '/guide/confirmReserve',
  guideRejectReserve: '/guide/rejectReserve',
  guideDeleteReserve: '/guide/delReserve',

  // --- Company ---
  companyShop: '/company/shop',
  companyShopAdd: '/company/shopAdd',
  companyShopInfo: '/company/shopInfo',
  companyShopEdit: '/company/shopEdit',
  companyShopDel: '/company/shopDel',
  companyReserve: '/company/reserve',
  companyReserveInfo: '/company/reserveInfo',
  companyConfirmReserve: '/company/confirmReserve',
  companyRejectReserve: '/company/rejectReserve',
  companyDeleteReserve: '/company/delReserve',
  companyInfo: '/company/info',

  // --- Integral ---
  integralUserDetails: '/integral/userDetails',
  integralGoodsClass: '/integral/goodsClass',
  integralGoods: '/integral/goods',
  integralGoodsInfo: '/integral/goodsInfo',
  integralExchange: '/integral/exchange',
  integralExchangeOrders: '/integral/exchangeOrders',
  integralExchangeOrderInfo: '/integral/exchangeOrderInfo',

  // --- VIP ---
  vipAbility: '/vip/ability',
  vipGuide: '/vip/guide',
  vipCompany: '/vip/company',
  vipSubscribeGuide: '/vip/subscriptionGuide',
  vipSubscribeCompany: '/vip/subscriptionCompany',
  vipPayStatus: '/vip/payStatus',

  // --- Message ---
  messageList: '/message/lists',
  messageMyEvaluate: '/message/myEvaluate',
  messageEvaluateMe: '/message/evaluateMy',
  followClass: '/message/followClass',
  messageMyFollow: '/message/myFollow',
  messageFollowMe: '/message/followMy',
  messageFollowMyShop: '/message/followMyShop',
  messageSystem: '/message/system',
  messageFollow: '/message/follow',
  messageUnFollowShop: '/message/unFollowShop',

  // --- Payment ---
  paymentWebhook: '/payment/webhook',
};
